version: '3'

services:
  poller:
    build:
      context: .
      dockerfile: poller.Dockerfile
    environment:
      - NODE_ENV=development-docker
      - VAULT_TOKEN=myroot
    depends_on:
      - worker
    networks:
      - private
    restart: on-failure

  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    environment:
      - NODE_ENV=development-docker
    ports:
      - "50051:50051"
    networks:
      - private
      # needs to be able to access internet
      - public
    restart: on-failure

  vault:
    image: vault:1.4.3
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    networks:
      - private
      - public
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot

networks:
  public:
  private:
    internal: true
