version: '3'

services:
  poller:
    command: nodemon conductor-poller/start-conductor-poller.js
    networks:
      - private
      - public
    volumes:
      - .:/http-worker

  worker:
    command: nodemon http-worker/httpworker-grpc-server
    networks:
      - private
      - public
    volumes:
      - .:/http-worker
