version: '3'

services:
  poller:
    build: .
    environment:
      - NODE_ENV=development-docker
      - VAULT_TOKEN=myroot
    command: bash -c "node /http-worker/conductor-poller/start-conductor-poller.js"
    depends_on:
      - worker
    networks:
      - private

  worker:
    build: .
    environment:
      - NODE_ENV=development-docker
      - VAULT_TOKEN=myroot
    command: bash -c "node /http-worker/http-worker/httpworker-grpc-server"
    ports:
      - "50051:50051"
    networks:
      - private

  vault:
    image: vault:1.4.3
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    networks:
      - private
      - public
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot

networks:
  public:
  private:
    internal: true
